language: node_js
node_js:
- '0.10'
- '0.8'
before_install:
- npm install -g grunt-cli
after_success:
- travis/success.sh
env:
  global:
    secure: MvbyenaGUUqRBJ0GWF8cPiY5KdBGKsqrrJNqjCIXFgMLtqc41gEpCirJw5/cBQiVIdyt8mEUolQjUe8JXo5fW7m+cvESOaBmSlT6aJ25qOMxcqBQ8B163cUPz1LRZoYBXgEak21DdC4cbG+zROX3TUiAPj4mwVnDO5Cj7VkLx4I=
